# Project Information
site_name: CTF Wiki
site_description: CTF Wiki
site_author: CTF Wiki Team
site_url: https://ctf-wiki.github.io/ctf-wiki/

# Repository
repo_name: 'ctf-wiki/ctf-wiki'
repo_url: 'https://github.com/ctf-wiki/ctf-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 CTF Wiki Team'

# Contents
nav:
    - Introduction:
        - Getting Started: index.md 
        - CTF History: introduction/history-zh.md
        - Introduction to CTF Competition Form: introduction/mode-zh.md
        - CTF Contest Content: introduction/content-zh.md
        - Offline Attack and Defense Experience Summary: introduction/experience-zh.md
        - CGC Super Challenge: introduction/cgc-zh.md
        - Learning Resources: introduction/resources-zh.md

    - Misc:
        - Miscellaneous Introduction: misc/introduction-zh.md
        - Information Gathering Technology: misc/recon-zh.md
        - Code Analysis:
            - Commonly Used Coding in the Communication Field: misc/encode/communication-zh.md
            - Computer Related Coding: misc/encode/computer-zh.md
            - Commonly Used Encodings in the Real World: misc/encode/modern-zh.md
        - Forensic Steganography: misc/prefix-zh.md
        - Image Analysis:
            - Introduction to Image Analysis: misc/picture/introduction-zh.md
            - PNG: misc/picture/png-zh.md 
            - JPG: misc/picture/jpg-zh.md 
            - GIF: misc/picture/gif-zh.md 
        - Traffic Packet Analysis:
            - Introduction to Traffic Packet Analysis: misc/traffic/introduction-zh.md
            - PCAP File Repairing: misc/traffic/fix-zh.md
            - Protocol Analysis:
                - Overview of Protocol Analysis: misc/traffic/protocols/README-zh.md
                - Wireshark: misc/traffic/protocols/Wireshark-zh.md 
                - HTTP: misc/traffic/protocols/HTTP-zh.md 
                - HTTPS: misc/traffic/protocols/HTTPS-zh.md 
                - FTP: misc/traffic/protocols/FTP-zh.md 
                - DNS: misc/traffic/protocols/DNS-zh.md 
                - WIFI: misc/traffic/protocols/WIFI-zh.md 
                - USB: misc/traffic/protocols/USB-zh.md 
            - Data Extraction: misc/traffic/data-zh.md
        - Compressed Package Analysis:
            - ZIP Format: misc/archive/zip-zh.md
            - RAR Format: misc/archive/rar-zh.md
        - Audio Steganography: misc/audio/introduction-zh.md
        - Disk Memory Analysis:
            - Introduction: misc/disk-memory/introduction-zh.md
            - Title: misc/disk-memory/problem-zh.md
        - Other:
            - pyc File: misc/other/pyc-zh.md
    - Crypto:
        - Introduction to Cryptography: crypto/introduction-zh.md
        - Basic Mathematics:
            - Introduction: crypto/basic/introduction-zh.md
        - Classical Cryptography:
            - Introduction to Classical Cryptography: crypto/classical/introduction-zh.md
            - Single table Substitution Cipher: crypto/classical/monoalphabetic-zh.md
            - Multi-table Substitution Cipher: crypto/classical/polyalphabetic-zh.md
            - Other Types of Cipher: crypto/classical/others-zh.md
            - Summary: crypto/classical/summary-zh.md
        - Stream Cipher:
            - Introduction: crypto/streamcipher/intro-zh.md
            - Pseudo Random Number Generator:
                - Introduction: crypto/streamcipher/prng/intro-zh.md
                - Cryptographic Security Pseudo-random Number Generator: crypto/streamcipher/prng/csprng-zh.md
                - Challenge Examples: crypto/streamcipher/prng/problem-zh.md 
            - Linear Congruence Generator:
                - Introduction: crypto/streamcipher/lcg/intro-zh.md
                - Example: crypto/streamcipher/lcg/challenge-zh.md
            - Feedback Shift Register:
                - Introduction: crypto/streamcipher/fsr/intro-zh.md
                - Linear Feedback Shift Register: crypto/streamcipher/fsr/lfsr-zh.md
                - Nonlinear Feedback Shift Register: crypto/streamcipher/fsr/nfsr-zh.md
            - Special Stream Cipher:
                - RC4: crypto/streamcipher/special/rc4-zh.md 
        - Block Cipher:
            - Introduction to Block Cipher: crypto/blockcipher/introduction-zh.md
            - ARX: crypto/blockcipher/arx-operations-zh.md 
            - DES: crypto/blockcipher/des-zh.md
            - IDEA: crypto/blockcipher/idea-zh.md 
            - AES: crypto/blockcipher/aes-zh.md 
            - Simon and Speck: crypto/blockcipher/simon-speck-zh.md 
            - Group Mode:
                - Introduction: crypto/blockcipher/mode/introduction-zh.md
                - Padding Methods: crypto/blockcipher/mode/padding-zh.md
                - ECB: crypto/blockcipher/mode/ecb-zh.md 
                - CBC: crypto/blockcipher/mode/cbc-zh.md 
                - PCBC: crypto/blockcipher/mode/pcbc-zh.md 
                - CFB: crypto/blockcipher/mode/cfb-zh.md 
                - OFB: crypto/blockcipher/mode/ofb-zh.md
                - CTR: crypto/blockcipher/mode/ctr-zh.md
                - Padding Oracle Attack: crypto/blockcipher/mode/padding-oracle-attack-zh.md 
        - Asymmetric Cryptography:
            - Introduction to Asymmetric Cryptography: crypto/asymmetric/introduction-zh.md
            - RSA:
                - RSA Introduction: crypto/asymmetric/rsa/rsa_theory-zh.md
                - Modulo-related Attacks: crypto/asymmetric/rsa/rsa_module_attack-zh.md
                - Public Key Index Related Attacks: crypto/asymmetric/rsa/rsa_e_attack-zh.md
                - Private Key d Related Attacks: crypto/asymmetric/rsa/rsa_d_attack-zh.md
                - Coppersmith Related Attacks: crypto/asymmetric/rsa/rsa_coppersmith_attack-zh.md
                - Chosen Plain Cipher Attack: crypto/asymmetric/rsa/rsa_chosen_plain_cipher-zh.md
                - Side Channel Attack: crypto/asymmetric/rsa/rsa_side_channel-zh.md
                - Bleichenbacher Attack: crypto/asymmetric/rsa/rsa_pkcs_attack-zh.md
                - Challenge Examples: crypto/asymmetric/rsa/rsa_complex-zh.md
            - Knapsack Cipher: crypto/asymmetric/knapsack/knapsack-zh.md
            - Discrete Log Correlation:
                - Discrete Logarithm: crypto/asymmetric/discrete-log/discrete-log-zh.md
                - Elgamal: crypto/asymmetric/discrete-log/elgamal-zh.md 
                - ECC: crypto/asymmetric/discrete-log/ecc-zh.md
            - Lattice-based Cryptography:
                - Lattice Overview: crypto/asymmetric/lattice/overview-zh.md
                - Introduction to Lattices: crypto/asymmetric/lattice/introduction-zh.md
                - Lattice-based Algorithm: crypto/asymmetric/lattice/lattice-reduction-zh.md
                - CVP: crypto/asymmetric/lattice/cvp-zh.md
        - Hash Function:
            - Introduction to the Hash Function: crypto/hash/introduction-zh.md
            - MD5: crypto/hash/md5-zh.md 
            - SHA1: crypto/hash/sha1-zh.md
            - FNV: crypto/hash/fnv-zh.md 
            - Hash Attack: crypto/hash/attack-zh.md 
            - Challenge Examples: crypto/hash/complex-zh.md
        - Digital Signature:
            - Introduction to Digital Signatures: crypto/signature/introduction-zh.md
            - RSA Digital Signature: crypto/signature/rsa-zh.md
            - ElGamal Digital Signature: crypto/signature/elgamal-zh.md
            - DSA Digital Signature: crypto/signature/dsa-zh.md
        - Summary of Attack Techniques:
            - Introduction: crypto/attack-summary/attack-mode-zh.md
            - Intermediate Encounter Attack: crypto/attack-summary/meet-in-the-middle-zh.md
            - Bit attack: crypto/attack-summary/bit-attack-zh.md
        - Certificate Format: crypto/certificate/introduction-zh.md
    - Web:
        - Introduction to Web Applications: web/introduction-zh.md
        - SQL Injection: web/sqli-zh.md
        - XSS Cross-site Scripting Attack: web/xss-zh.md
        - CSRF Cross-site Request Forgery: web/csrf-zh.md
        - SSRF Server Request Forgery: web/ssrf-zh.md
        - PHP Code Auditing: web/php/php-zh.md
    - Assembly:
        - x86_x64: assembly/x86-x64/readme-zh.md 
        - mips: assembly/mips/readme-zh.md 
        - arm: assembly/arm/readme-zh.md 
    - Executable: 
        - ELF file:
            - ELF File Basic Structure: executable/elf/elf-structure-zh.md
            - Program Loading: executable/elf/program-loading-zh.md
            - Program Link: executable/elf/program-linking-zh.md
            - Program Execution Flow: executable/elf/running-overview-zh.md
        - PE file:
            - PE File Basic Structure: executable/pe/pe-excutable-zh.md
            - PE Import Table: executable/pe/pe-import-table-zh.md
            - PE Export Table: executable/pe/pe-export-table-zh.md
            - PE Relocation Table: executable/pe/pe-relocation-table-zh.md
    - Reverse Engineering:
        - Reverse Overview:
            - Software Reverse Engineering Introduction: reverse/introduction-zh.md
            - Common Encryption Algorithms and Code Recognition: reverse/Identify-Encode-Encryption/introduction-zh.md
            - Labyrinth Problem: reverse/maze/maze-zh.md
            - Virtual Machine Command Analysis: reverse/vm/vm-zh.md
            - Unicorn Engine Introduction: reverse/unicorn/introduction-zh.md 
        - Linux Reverse:
            - Linux Reverse Technology:
                - LD_PRELOAD: reverse/linux/ld_preload-zh.md 
                - Incorrect Disassembly Fix: reverse/linux/false-disasm-zh.md 
                - Detecting Breakpoints Bypassing: reverse/linux/detect-bp-zh.md 
                - Detecting Debugging Bypassing: reverse/linux/detect-dbg-zh.md 
        - Windows Reverse: 
            - Shelling Technology:
                - Introduction to the Protective case: reverse/windows/unpack/packer-introduction-zh.md
                - Single Step Tracking Method: reverse/windows/unpack/trace-zh.md
                - ESP Law: reverse/windows/unpack/esp-zh.md
                - One Step to the OEP Method: reverse/windows/unpack/direct-oep-zh.md
                - Memory Mirroring Method: reverse/windows/unpack/memory-zh.md
                - Last Exception Method: reverse/windows/unpack/last-exception-zh.md
                - SFX Method: reverse/windows/unpack/sfx-zh.md
                - DUMP and IAT Reconstruction: reverse/windows/unpack/fix-iat-zh.md
                - Manually Find the IAT and Rebuild It Using ImportREC: reverse/windows/unpack/manually-fix-iat-zh.md
                - DLL File Unpacking: reverse/windows/unpack/unpack-dll-zh.md
            - Anti-debugging Technology:
                - NtGlobalFlag: reverse/windows/anti-debug/ntglobalflag-zh.md 
                - Heap Flags: reverse/windows/anti-debug/heap-flags-zh.md 
                - The Heap: reverse/windows/anti-debug/the-heap-zh.md 
                - Interrupt 3: reverse/windows/anti-debug/int-3-zh.md 
                - IsDebuggerPresent: reverse/windows/anti-debug/isdebuggerpresent-zh.md 
                - CheckRemoteDebuggerPresent: reverse/windows/anti-debug/checkremotedebuggerpresent-zh.md 
                - NtQueryInformationProcess: reverse/windows/anti-debug/ntqueryinformationprocess-zh.md 
                - Flower command: reverse/windows/anti-debug/junk-code-zh.md
                - Anti-debug technical example: reverse/windows/anti-debug/example-zh.md
    - Pwn:
        - Pwn Overview:
            - pwn/readme-zh.md 
        - Linux Pwn:
            - Security Protection Mechanism:
                - Canary: pwn/linux/mitigation/canary-zh.md 
            - Stack Overflow:
                - Stack Introduction: pwn/linux/stackoverflow/stack-intro-zh.md
                - Stack Overflow Principle: pwn/linux/stackoverflow/stackoverflow-basic-zh.md
                - Basic ROP: pwn/linux/stackoverflow/basic-rop-zh.md 
                - Intermediate ROP: pwn/linux/stackoverflow/medium-rop-zh.md
                - Advanced ROP: pwn/linux/stackoverflow/advanced-rop-zh.md
                - ROP Tricks: pwn/linux/stackoverflow/fancy-rop-zh.md
            - Format String Vulnerability:
                - Format String Vulnerability Principle: pwn/linux/fmtstr/fmtstr_intro-zh.md
                - Format String Exploit: pwn/linux/fmtstr/fmtstr_exploit-zh.md
                - Format String Vulnerability Example: pwn/linux/fmtstr/fmtstr_example-zh.md
                - Format String Vulnerability Detection: pwn/linux/fmtstr/fmtstr_detect-zh.md
            - Glibc Heap Related:
                - Introduction to Heap: pwn/linux/glibc-heap/introduction-zh.md
                - Heap Overview: pwn/linux/glibc-heap/heap_overview-zh.md
                - Heap Related Data Structure: pwn/linux/glibc-heap/heap_structure-zh.md
                - In-depth Understanding of Ptmalloc2:
                    - Implementation: pwn/linux/glibc-heap/implementation/overview-zh.md 
                    - Basic Functions in the heap implementation: pwn/linux/glibc-heap/implementation/basic-zh.md
                    - Heap Initialization: pwn/linux/glibc-heap/implementation/heap-init-zh.md
                    - Allocate Heap Memory: pwn/linux/glibc-heap/implementation/malloc-zh.md
                    - Free Heap Memory: pwn/linux/glibc-heap/implementation/free-zh.md
                    - Tcache: pwn/linux/glibc-heap/implementation/tcache-zh.md
                    - malloc_state: pwn/linux/glibc-heap/implementation/malloc_state-zh.md 
                    - Other: pwn/linux/glibc-heap/implementation/misc-zh.md 
                - Heap Overflow: pwn/linux/glibc-heap/heapoverflow_basic-zh.md
                - Heap-based Off-By-One: pwn/linux/glibc-heap/off_by_one-zh.md
                - Chunk Extend/Overlapping: pwn/linux/glibc-heap/chunk_extend_overlapping-zh.md 
                - Unlink: pwn/linux/glibc-heap/unlink-zh.md
                - Use After Free: pwn/linux/glibc-heap/use_after_free-zh.md
                - Fastbin Attack: pwn/linux/glibc-heap/fastbin_attack-zh.md
                - Unsorted Bin Attack: pwn/linux/glibc-heap/unsorted_bin_attack-zh.md
                - Large Bin Attack: pwn/linux/glibc-heap/large_bin_attack-zh.md
                - Tcache Attack: pwn/linux/glibc-heap/tcache_attack-zh.md
                - House of Einherjar: pwn/linux/glibc-heap/house_of_einherjar-zh.md
                - House of Force: pwn/linux/glibc-heap/house_of_force-zh.md
                - House of Lore: pwn/linux/glibc-heap/house_of_lore-zh.md
                - House of Orange: pwn/linux/glibc-heap/house_of_orange-zh.md
                - House of Rabbit: pwn/linux/glibc-heap/house_of_rabbit-zh.md
                - House of Roman: pwn/linux/glibc-heap/house_of_roman-zh.md 
            - IO_FILE Related:
                - FILE Structure Description: pwn/linux/io_file/introduction-zh.md
                - Forged Vtable to Hijack Control Flow: pwn/linux/io_file/fake-vtable-exploit-zh.md
                - FSOP: pwn/linux/io_file/fsop-zh.md
                - Use of IO_FILE Under Glibc 2.24: pwn/linux/io_file/exploit-in-libc2.24-zh.md
            - Race Condition:
                - Race Condition Introduction: pwn/linux/race-condition/introduction-zh.md
                - Example: pwn/linux/race-condition/problem-zh.md
            - Integer Overflow:
                - Introduction to The Principle of Integer Overflow: pwn/linux/integeroverflow/intof-zh.md
            - Sandbox Escape:
                - Python Sandbox Escape: pwn/linux/sandbox/python-sandbox-escape-zh.md
            - Linux Kernel: 
                - Environment Setup: pwn/linux/kernel/environment-zh.md
                - Basics: pwn/linux/kernel/basic_knowledge-zh.md
                - Kernel-UAF: pwn/linux/kernel/kernel_uaf-zh.md
                - Kernel-ROP: pwn/linux/kernel/kernel_rop-zh.md
                - ret2usr: pwn/linux/kernel/ret2usr-zh.md
                - bypass-smep: pwn/linux/kernel/bypass_smep-zh.md
                - Double Fetch: pwn/linux/kernel/double-fetch-zh.md
            - arm-pwn:
                - Environment Setup: pwn/linux/arm/environment-zh.md
                - arm-rop: pwn/linux/arm/arm_rop-zh.md
            - Summary:
                - Address Leaking: pwn/linux/summary/get-address-zh.md
                - Hijack Control Flow: pwn/linux/summary/hijack-control-flow-zh.md
                - Get Shell: pwn/linux/summary/get-shell-zh.md

        - Windows Pwn:
            - Overview: pwn/windows/readme-zh.md
            - Stack Overflow:
                - Stack Introduction: pwn/windows/stackoverflow/stack-introduce-zh.md
                - Stack Overflow Principle: pwn/windows/stackoverflow/stackoverflow-basic-zh.md
                - shellcode-in-stack: pwn/windows/stackoverflow/shellcode-in-stack-zh.md
    
    - Android:
        - Android Development Basics: android/basic_develop/basic_develop-zh.md
        - Android Application Operating Mechanism Brief:
            - Basics: android/basic_operating_mechanism/readme-zh.md 
            - The Operating Mechanism of the Java Layer in Android: 
                - Andriod Native: android/basic_operating_mechanism/java_layer/readme-zh.md 
                - Smali Introduction: android/basic_operating_mechanism/java_layer/smali/smali-zh.md 
                - Dex and ODEX:
                    - DEX: android/basic_operating_mechanism/java_layer/dex/dex-zh.md 
                    - ODEX: android/basic_operating_mechanism/java_layer/dex/odex-zh.md 
            - Android Native Layer Introduction:
                - Android SO: android/basic_operating_mechanism/native_layer/so-zh.md

            - Android Reverse Basic Introduction:
                - Brief Description: android/basic_reverse/overview-zh.md
                - Android Key Part Location: android/basic_reverse/android_code_location-zh.md
                - Android Simple Static Analysis:
                    - Android Java Layer Static Analysis: android/basic_reverse/static/java-example-zh.md
                    - Android Native Layer Static Analysis: android/basic_reverse/static/so-example-zh.md
                    - Android Static Analysis Hybrid Example: android/basic_reverse/static/complex-example-zh.md
                - Android Simple Dynamic Analysis:
                    - Dynamic Debugging: android/basic_reverse/dynamic/dynamic_debug-zh.md
                    - Android Dynamic Debugging SO: android/basic_reverse/dynamic/ida_native_debug-zh.md
    - ICS:
        - ICS_CTF Contest: ics/ctfs-zh.md
        - ICS_CTF found: ics/discover-zh.md
        - ICS_CTF uses: ics/exploit-zh.md
        - ICS_CTF Learning Resources: ics/learn-zh.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true 
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'ctf-wiki'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - '_static/js/extra.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
    - '_static/css/extra.css'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false 
    - def_list 
    - footnotes 
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
