# Project Information
site_name: CTF Wiki
site_description: CTF Wiki
site_author: CTF Wiki Team
site_url: https://ctf-wiki.github.io/ctf-wiki/

# Repository
repo_name: 'ctf-wiki/ctf-wiki'
repo_url: 'https://github.com/ctf-wiki/ctf-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 CTF Wiki Team'

# Contents
nav:
  - Introduction:
    - Getting Started: index.md
    - CTF 历史: introduction/history.md
    - CTF 竞赛模式简介: introduction/mode.md
    - CTF 竞赛内容: introduction/content.md
    - 线下攻防经验小结: introduction/experience.md
    - CGC 超级挑战赛: introduction/cgc.md
    - 学习资源: introduction/resources.md
  - Misc:
    - 杂项简介: misc/introduction.md
    - 信息搜集技术: misc/recon.md
    - 编码分析:
      - 通信领域常用编码: misc/encode/communication.md
      - 计算机相关的编码: misc/encode/computer.md
      - 现实世界中常用的编码: misc/encode/modern.md
    - 取证隐写前置技术: misc/prefix.md
    - 图片分析:
      - 图片分析简介: misc/picture/introduction.md
      - PNG: misc/picture/png.md
      - JPG: misc/picture/jpg.md
      - GIF: misc/picture/gif.md
    - 流量包分析:
      - 流量包分析简介: misc/traffic/introduction.md
      - PCAP 文件修复: misc/traffic/fix.md
      - 协议分析:
        - 协议分析概述: misc/traffic/protocols/README.md
        - Wireshark: misc/traffic/protocols/Wireshark.md
        - HTTP: misc/traffic/protocols/HTTP.md
        - HTTPS: misc/traffic/protocols/HTTPS.md
        - FTP: misc/traffic/protocols/FTP.md
        - DNS: misc/traffic/protocols/DNS.md
        - WIFI: misc/traffic/protocols/WIFI.md
        - USB: misc/traffic/protocols/USB.md
      - 数据提取: misc/traffic/data.md
    - 压缩包分析:
      - ZIP 格式: misc/archive/zip.md
      - RAR 格式: misc/archive/rar.md
    - 音频隐写: misc/audio/introduction.md
    - 磁盘内存分析:
      - 介绍: misc/disk-memory/introduction.md
      - 题目: misc/disk-memory/problem.md
    - Other:
      - pyc文件: misc/other/pyc.md
  - Crypto:
    - 密码学简介: crypto/introduction.md
    - 基础数学知识:
      - 简介: crypto/basic/introduction.md
    - 古典密码:
      - 古典密码简介: crypto/classical/introduction.md
      - 单表代换加密: crypto/classical/monoalphabetic.md
      - 多表代换加密: crypto/classical/polyalphabetic.md
      - 其他类型加密: crypto/classical/others.md
      - 总结: crypto/classical/summary.md
    - 流密码:
      - 介绍: crypto/streamcipher/intro.md
      - 伪随机数生成器:
        - 介绍: crypto/streamcipher/prng/intro.md
        - 密码学安全伪随机数生成器: crypto/streamcipher/prng/csprng.md
        - 题目: crypto/streamcipher/prng/problem.md
      - 线性同余生成器:
        - 简介: crypto/streamcipher/lcg/intro.md
        - 例题: crypto/streamcipher/lcg/challenge.md
      - 反馈移位寄存器:
        - 介绍: crypto/streamcipher/fsr/intro.md
        - 线性反馈移位寄存器: crypto/streamcipher/fsr/lfsr.md
        - 非线性反馈移位寄存器: crypto/streamcipher/fsr/nfsr.md
      - 特殊流密码:
        - RC4: crypto/streamcipher/special/rc4.md
    - 块加密:
      - 块加密简介: crypto/blockcipher/introduction.md
      - ARX: crypto/blockcipher/arx-operations.md
      - DES: crypto/blockcipher/des.md
      - IDEA: crypto/blockcipher/idea.md
      - AES: crypto/blockcipher/aes.md
      - Simon and Speck: crypto/blockcipher/simon-speck.md
      - 分组模式:
        - 介绍: crypto/blockcipher/mode/introduction.md
        - 填充方式: crypto/blockcipher/mode/padding.md
        - ECB: crypto/blockcipher/mode/ecb.md
        - CBC: crypto/blockcipher/mode/cbc.md
        - PCBC: crypto/blockcipher/mode/pcbc.md
        - CFB: crypto/blockcipher/mode/cfb.md
        - OFB: crypto/blockcipher/mode/ofb.md
        - CTR: crypto/blockcipher/mode/ctr.md
        - Padding Oracle Attack: crypto/blockcipher/mode/padding-oracle-attack.md
    - 非对称加密:
      - 非对称加密简介: crypto/asymmetric/introduction.md
      - RSA:
        - RSA 基本介绍: crypto/asymmetric/rsa/rsa_theory.md
        - 模数相关攻击: crypto/asymmetric/rsa/rsa_module_attack.md
        - 公钥指数相关攻击: crypto/asymmetric/rsa/rsa_e_attack.md
        - 私钥 d 相关攻击: crypto/asymmetric/rsa/rsa_d_attack.md
        - Coppersmith 相关攻击: crypto/asymmetric/rsa/rsa_coppersmith_attack.md
        - 选择明密文攻击: crypto/asymmetric/rsa/rsa_chosen_plain_cipher.md
        - 侧信道攻击: crypto/asymmetric/rsa/rsa_side_channel.md
        - Bleichenbacher 攻击: crypto/asymmetric/rsa/rsa_pkcs_attack.md
        - 综合: crypto/asymmetric/rsa/rsa_complex.md
      - 背包加密: crypto/asymmetric/knapsack/knapsack.md
      - 离散对数相关:
        - 离散对数: crypto/asymmetric/discrete-log/discrete-log.md
        - Elgamal: crypto/asymmetric/discrete-log/elgamal.md
        - ECC: crypto/asymmetric/discrete-log/ecc.md
      - 格密码:
        - 格概述: crypto/asymmetric/lattice/overview.md
        - 格介绍: crypto/asymmetric/lattice/introduction.md
        - 格基规约算法: crypto/asymmetric/lattice/lattice-reduction.md
    - 哈希函数:
      - 哈希函数简介: crypto/hash/introduction.md
      - MD5: crypto/hash/md5.md
      - SHA1: crypto/hash/sha1.md
      - FNV: crypto/hash/fnv.md
      - Hash Attack: crypto/hash/attack.md
      - 综合: crypto/hash/complex.md
    - 数字签名:
      - 数字签名简介: crypto/signature/introduction.md
      - RSA 数字签名: crypto/signature/rsa.md
      - ElGamal 数字签名: crypto/signature/elgamal.md
      - DSA 数字签名: crypto/signature/dsa.md
    - 攻击思想总结:
      - 简介: crypto/attack-summary/attack-mode.md
      - 中间相遇攻击: crypto/attack-summary/meet-in-the-middle.md
      - 比特攻击: crypto/attack-summary/bit-attack.md
    - 证书格式: crypto/certificate/introduction.md
  - Web:
    - Web 应用简介: web/introduction.md
    - SQL 注入: web/sqli.md
    - XSS 跨站脚本攻击: web/xss.md
    - CSRF 跨站请求伪造: web/csrf.md
    - SSRF 服务端请求伪造: web/ssrf.md
    - PHP 代码审计: web/php/php.md
  - Assembly:
    - x86_x64: assembly/x86-x64/readme.md
    - mips: assembly/mips/readme.md
    - arm: assembly/arm/readme.md
  - Executable:
    - ELF 文件:
      - ELF文件基本结构: executable/elf/elf-structure.md
      - 程序加载: executable/elf/program-loading.md
      - 程序链接: executable/elf/program-linking.md
      - 程序执行流程: executable/elf/running-overview.md
  - Reverse:
    - Reverse Overview:
      - 软件逆向工程简介: reverse/introduction.md
      - 常见加密算法和编码识别: reverse/Identify-Encode-Encryption/introduction.md
      - 迷宫问题: reverse/maze/maze.md
      - 虚拟机指令分析: reverse/vm/vm.md
      - Unicorn Engine 简介: reverse/unicorn/introduction.md
    - Linux Reverse:
      - Linux 逆向技术:
        - LD_PRELOAD: reverse/linux/ld_preload.md
        - False Disassembly: reverse/linux/false-disasm.md
        - Detecting Breakpoints: reverse/linux/detect-bp.md
        - Detecting debugging: reverse/linux/detect-dbg.md
    - Windows Reverse:
      - 脱壳技术:
        - 保护壳简介: reverse/windows/unpack/packer-introduction.md
        - 单步跟踪法: reverse/windows/unpack/trace.md
        - ESP 定律法: reverse/windows/unpack/esp.md
        - 一步到达 OEP 法: reverse/windows/unpack/direct-oep.md
        - 内存镜像法: reverse/windows/unpack/memory.md
        - 最后一次异常法: reverse/windows/unpack/last-exception.md
        - SFX 法: reverse/windows/unpack/sfx.md
        - DUMP 及 IAT 重建: reverse/windows/unpack/fix-iat.md
        - 手动查找 IAT 并使用 ImportREC 重建: reverse/windows/unpack/manually-fix-iat.md
        - DLL 文件脱壳: reverse/windows/unpack/unpack-dll.md
      - 反调试技术:
        - NtGlobalFlag: reverse/windows/anti-debug/ntglobalflag.md
        - Heap Flags: reverse/windows/anti-debug/heap-flags.md
        - The Heap: reverse/windows/anti-debug/the-heap.md
        - Interrupt 3: reverse/windows/anti-debug/int-3.md
        - IsDebuggerPresent: reverse/windows/anti-debug/isdebuggerpresent.md
        - CheckRemoteDebuggerPresent: reverse/windows/anti-debug/checkremotedebuggerpresent.md
        - NtQueryInformationProcess: reverse/windows/anti-debug/ntqueryinformationprocess.md
        - 花指令: reverse/windows/anti-debug/junk-code.md
        - 反调试技术例题: reverse/windows/anti-debug/example.md
  - Pwn:
    - Pwn Overview:
        - pwn/readme.md
    - Linux Pwn:
      - 安全防护机制:
        - canary: pwn/linux/mitigation/canary.md
      - 栈溢出:
        - 栈介绍: pwn/linux/stackoverflow/stack-intro.md
        - 栈溢出原理: pwn/linux/stackoverflow/stackoverflow-basic.md
        - 基本 ROP: pwn/linux/stackoverflow/basic-rop.md
        - 中级 ROP: pwn/linux/stackoverflow/medium-rop.md
        - 高级 ROP: pwn/linux/stackoverflow/advanced-rop.md
        - 花式栈溢出: pwn/linux/stackoverflow/fancy-rop.md
      - 格式化字符串漏洞:
        - 格式化字符串漏洞原理介绍: pwn/linux/fmtstr/fmtstr_intro.md
        - 格式化字符串漏洞利用: pwn/linux/fmtstr/fmtstr_exploit.md
        - 格式化字符串漏洞例子: pwn/linux/fmtstr/fmtstr_example.md
        - 格式化字符串漏洞检测: pwn/linux/fmtstr/fmtstr_detect.md
      - Glibc Heap 利用:
        - 堆利用简介: pwn/linux/glibc-heap/introduction.md
        - 堆概述: pwn/linux/glibc-heap/heap_overview.md
        - 堆相关数据结构: pwn/linux/glibc-heap/heap_structure.md
        - 深入理解 Ptmalloc2:
            - 概述: pwn/linux/glibc-heap/implementation/overview.md
            - 堆中的基本函数: pwn/linux/glibc-heap/implementation/basic.md
            - 堆初始化: pwn/linux/glibc-heap/implementation/heap-init.md
            - 申请堆内存: pwn/linux/glibc-heap/implementation/malloc.md
            - 释放堆内存: pwn/linux/glibc-heap/implementation/free.md
            - Tcache: pwn/linux/glibc-heap/implementation/tcache.md
            - malloc_state: pwn/linux/glibc-heap/implementation/malloc_state.md
            - 杂: pwn/linux/glibc-heap/implementation/misc.md
        - 堆溢出: pwn/linux/glibc-heap/heapoverflow_basic.md
        - 堆中的 Off-By-One: pwn/linux/glibc-heap/off_by_one.md
        - Unlink: pwn/linux/glibc-heap/unlink.md
        - Use After Free: pwn/linux/glibc-heap/use_after_free.md
        - Fastbin Attack: pwn/linux/glibc-heap/fastbin_attack.md
        - Tcache 利用: pwn/linux/glibc-heap/tcache_attack.md
        - Chunk Extend / Overlapping: pwn/linux/glibc-heap/chunk_extend_overlapping.md
        - House Of Einherjar: pwn/linux/glibc-heap/house_of_einherjar.md
        - House of Lore: pwn/linux/glibc-heap/house_of_lore.md
        - House Of Force: pwn/linux/glibc-heap/house_of_force.md
        - Unsorted Bin Attack: pwn/linux/glibc-heap/unsorted_bin_attack.md
        - House of Orange: pwn/linux/glibc-heap/house_of_orange.md
        - House of Rabbit: pwn/linux/glibc-heap/house_of_rabbit.md
        - House of Roman: pwn/linux/glibc-heap/house_of_roman.md
      - IO_FILE 利用:
        - FILE 文件结构介绍: pwn/linux/io_file/introduction.md
        - 伪造 vtable 劫持程序流程: pwn/linux/io_file/fake-vtable-exploit.md
        - FSOP: pwn/linux/io_file/fsop.md
        - 新版本 libc 下 IO_FILE 的利用: pwn/linux/io_file/exploit-in-libc2.24.md
      - 条件竞争:
        - 条件竞争介绍: pwn/linux/race-condition/introduction.md
        - 例题: pwn/linux/race-condition/problem.md
      - 整数溢出:
        - 整数溢出原理介绍: pwn/linux/integeroverflow/intof.md
      - 沙箱逃逸:
        - Python沙箱逃逸: pwn/linux/sandbox/python-sandbox-escape.md
      - arm-pwn:
        - 环境搭建: pwn/linux/arm/environment.md
        - arm-rop: pwn/linux/arm/arm_rop.md
      - kernel:
        - 环境搭建: pwn/linux/kernel/environment.md
        - 基础知识: pwn/linux/kernel/basic_knowledge.md
        - kernel-UAF: pwn/linux/kernel/kernel_uaf.md
        - kernel-ROP: pwn/linux/kernel/kernel_rop.md
        - ret2usr: pwn/linux/kernel/ret2usr.md
        - bypass-smep: pwn/linux/kernel/bypass_smep.md
      - Summary:
        - 获取地址: pwn/linux/summary/get-address.md
        - 控制程序执行流: pwn/linux/summary/hijack-control-flow.md
        - get shell: pwn/linux/summary/get-shell.md
    - Windows Pwn:
      - 概述: pwn/windows/readme.md
      - 栈溢出:
        - 栈介绍: pwn/windows/stackoverflow/stack-introduce.md
        - 栈溢出原理: pwn/windows/stackoverflow/stackoverflow-basic.md
        - shellcode-in-stack: pwn/windows/stackoverflow/shellcode-in-stack.md
  - Android:
    - Android 开发基础: android/basic_develop/basic_develop.md
    - Android 运行机制简述:
      - 简述: android/basic_operating_mechanism/readme.md
      - Android 中 Java 层的运行机制:
        - 简述: android/basic_operating_mechanism/java_layer/readme.md
        - Smali 介绍: android/basic_operating_mechanism/java_layer/smali/smali.md
        - Dex && ODEX:
          - DEX: android/basic_operating_mechanism/java_layer/dex/dex.md
          - ODEX: android/basic_operating_mechanism/java_layer/dex/odex.md
      - Android Native 层介绍:
        - Android So 介绍: android/basic_operating_mechanism/native_layer/so.md
    - Android 逆向基本介绍:
      - 简述: android/basic_reverse/overview.md
      - Android 关键代码定位: android/basic_reverse/android_code_location.md
      - Android 简单静态分析:
        - Android Java 层静态分析: android/basic_reverse/static/java-example.md
        - Android Native 层静态分析: android/basic_reverse/static/so-example.md
        - Android 静态分析混合例子: android/basic_reverse/static/complex-example.md
      - Android 简单动态分析:
        - 简述: android/basic_reverse/dynamic/dynamic_debug.md
        - Android 动态调试 So: android/basic_reverse/dynamic/ida_native_debug.md
  - ICS:
    - ICS_CTF 竞赛: ics/ctfs.md
    - ICS_CTF 发现: ics/discover.md
    - ICS_CTF 利用: ics/exploit.md
    - ICS_CTF 学习资源: ics/learn.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'ctf-wiki'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
  - '_static/js/extra.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
