# Project Information
site_name: CTF Wiki
site_description: CTF Wiki
site_author: CTF Wiki Team
site_url: https://ctf-wiki.github.io/ctf-wiki/

# Repository
repo_name: 'ctf-wiki/ctf-wiki'
repo_url: 'https://github.com/ctf-wiki/ctf-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 CTF Wiki Team'

# Contents
pages:
  - Introduction:
    - Getting Started: index.md
    - CTF 历史: introduction/history.md
    - CTF 竞赛模式简介: introduction/mode.md
    - CTF 竞赛内容: introduction/content.md
    - 线下攻防经验小结: introduction/experience.md
    - CGC 超级挑战赛: introduction/cgc.md
    - 学习资源: introduction/resources.md
  - Misc:
    - 杂项简介: misc/introduction.md
    - 信息搜集技术: misc/recon.md
    - 编码分析:
      - 通信领域常用编码: misc/encode/communication.md
      - 计算机相关的编码: misc/encode/computer.md
      - 现实世界中常用的编码: misc/encode/modern.md
    - 取证隐写前置技术: misc/prefix.md
    - 图片分析:
      - 图片分析简介: misc/picture/introduction.md
      - PNG: misc/picture/png.md
      - JPG: misc/picture/jpg.md
      - GIF: misc/picture/gif.md
    - 流量包分析:
      - 流量包分析简介: misc/traffic/introduction.md
      - PCAP 文件修复: misc/traffic/fix.md
      - 协议分析: misc/traffic/protocols.md
      - 数据提取: misc/traffic/data.md
    - 压缩包分析:
      - ZIP 格式: misc/archive/zip.md
      - RAR 格式: misc/archive/rar.md
    - 音频隐写: misc/audio/introduction.md
    - 磁盘内存分析: misc/disk-memory/introduction.md
    - Other: 
      - pyc文件: misc/other/pyc.md
  - Crypto:
    - 密码学简介: crypto/introduction.md
    - 古典密码:
      - 古典密码简介: crypto/classical/introduction.md
      - 单表代换加密: crypto/classical/monoalphabetic.md
      - 多表代换加密: crypto/classical/polyalphabetic.md
      - 其他类型加密: crypto/classical/others.md
      - 总结: crypto/classical/summary.md
    - 对称加密:
      - 对称加密简介: crypto/symmetric/introduction.md
      - DES: crypto/symmetric/des.md
      - AES: crypto/symmetric/aes.md
      - Simon and Speck: crypto/symmetric/simon-speck.md
      - 分组模式: crypto/symmetric/block-cipher.md
    - 非对称加密:
      - 非对称加密简介: crypto/asymmetric/introduction.md
      - RSA:
        - RSA 基本介绍: crypto/asymmetric/rsa/rsa_theory.md
        - 模数相关攻击: crypto/asymmetric/rsa/rsa_module_attack.md
        - 公钥指数相关攻击: crypto/asymmetric/rsa/rsa_e_attack.md
        - 私钥 d 相关攻击: crypto/asymmetric/rsa/rsa_d_attack.md
        - 选择密文攻击: crypto/asymmetric/rsa/rsa_chosen_cipher.md
        - Coppersmith 相关攻击: crypto/asymmetric/rsa/rsa_coppersmith_attack.md
        - 侧信道攻击: crypto/asymmetric/rsa/rsa_side_channel.md
        - Bleichenbacher 攻击: crypto/asymmetric/rsa/rsa_pkcs_attack.md
        - 综合: crypto/asymmetric/rsa/rsa_complex.md
      - 背包加密: crypto/asymmetric/knapsack/knapsack.md
      - 离散对数相关: crypto/asymmetric/discrete-log/discrete-log.md
    - 哈希函数:
      - 哈希函数简介: crypto/hash/introduction.md
      - MD5: crypto/hash/md5.md
      - SHA1: crypto/hash/sha1.md
      - Hash Attack: crypto/hash/attack.md
      - 综合: crypto/hash/complex.md
    - 数字签名:
      - 数字签名简介: crypto/signature/introduction.md
      - RSA 数字签名: crypto/signature/rsa.md
      - ElGamal 数字签名: crypto/signature/elgamal.md
      - DSA 数字签名: crypto/signature/dsa.md
    - 伪随机数:
      - 伪随机数生成器: crypto/prng/introduction.md
      - 密码学安全伪随机数生成器: crypto/prng/csprng.md
      - 例题: crypto/prng/problem.md 
    - 证书格式: crypto/certificate/introduction.md
  - Web:
    - Web 应用简介: web/introduction.md
    - SQL 注入: web/sqli.md
    - XSS 跨站脚本攻击: web/xss.md
    - CSRF 跨站请求伪造: web/csrf.md
    - SSRF 服务端请求伪造: web/ssrf.md
    - PHP 代码审计: web/php.md
  - Reverse:
    - 软件逆向工程简介: reverse/introduction.md
    - 脱壳技术:
      - 保护壳简介: reverse/unpack/packer-introduction.md
      - 单步跟踪法: reverse/unpack/trace.md
      - ESP 定律法: reverse/unpack/esp.md
      - 一步到达 OEP 法: reverse/unpack/direct-oep.md
      - 内存镜像法: reverse/unpack/memory.md
      - 最后一次异常法: reverse/unpack/last-exception.md
      - SFX 法: reverse/unpack/sfx.md
      - DUMP 及 IAT 重建: reverse/unpack/fix-iat.md
      - 手动查找 IAT 并使用 ImportREC 重建: reverse/unpack/manually-fix-iat.md
      - DLL 文件脱壳: reverse/unpack/unpack-dll.md
    - Unicorn Engine 简介: reverse/unicorn/introduction.md
    - 反调试技术:
      - NtGlobalFlag: reverse/anti-debug/ntglobalflag.md
      - Heap Flags: reverse/anti-debug/heap-flags.md
      - The Heap: reverse/anti-debug/the-heap.md
      - Interrupt 3: reverse/anti-debug/int-3.md
      - IsDebuggerPresent: reverse/anti-debug/isdebuggerpresent.md
      - CheckRemoteDebuggerPresent: reverse/anti-debug/checkremotedebuggerpresent.md
      - NtQueryInformationProcess: reverse/anti-debug/ntqueryinformationprocess.md
      - 花指令: reverse/anti-debug/junk-code.md
      - 反调试技术例题: reverse/anti-debug/example.md
    - Linux 逆向技术:
      - LD_PRELOAD: reverse/linux/ld_preload.md
      - False Disassembly: reverse/linux/false-disasm.md
      - Detecting Breakpoints: reverse/linux/detect-bp.md
      - Detecting debugging: reverse/linux/detect-dbg.md
  - Pwn:
    - 栈溢出:
      - 栈介绍: pwn/stackoverflow/stack_intro.md
      - 栈溢出原理: pwn/stackoverflow/stackoverflow_basic.md
      - 基本 ROP: pwn/stackoverflow/basic_rop.md
      - 花式栈溢出技巧: pwn/stackoverflow/others.md
      - 中级 ROP: pwn/stackoverflow/medium_rop.md
      - 高级 ROP: pwn/stackoverflow/advanced_rop.md
    - 格式化字符串漏洞:
      - 格式化字符串漏洞原理介绍: pwn/fmtstr/fmtstr_intro.md
      - 格式化字符串漏洞利用: pwn/fmtstr/fmtstr_exploit.md
      - 格式化字符串漏洞例子: pwn/fmtstr/fmtstr_example.md
      - 格式化字符串漏洞检测: pwn/fmtstr/fmtstr_detect.md
    - 堆利用:
      - 堆利用简介: pwn/heap/introduction.md
      - 堆概述: pwn/heap/heap_overview.md
      - 堆相关数据结构: pwn/heap/heap_structure.md
      - 深入理解堆的实现: pwn/heap/heap_implementation_details.md
      - 堆溢出: pwn/heap/heapoverflow_basic.md
      - 堆中的 Off-By-One: pwn/heap/off_by_one.md
      - Unlink: pwn/heap/unlink.md
      - Use After Free: pwn/heap/use_after_free.md
      - Fastbin Attack: pwn/heap/fastbin_attack.md
      - Chunk Extend / Shrink: pwn/heap/chunk_extend_shrink.md
      - House Of Einherjar: pwn/heap/house_of_einherjar.md
      - House of Lore: pwn/heap/house_of_lore.md
      - House Of Force: pwn/heap/house_of_force.md
      - Unsorted Bin Attack: pwn/heap/unsorted_bin_attack.md
      - House of Orange: pwn/heap/house_of_orange.md
    - IO_FILE 利用:
      - FILE 文件结构介绍: pwn/io_file/introduction.md
      - 伪造 vtable 劫持程序流程: pwn/io_file/fake-vtable-exploit.md
      - FSOP: pwn/io_file/fsop.md
      - 新版本 libc 下 IO_FILE 的利用: pwn/io_file/exploit-in-libc2.24.md
    - 条件竞争:
      - 条件竞争介绍: pwn/race-condition/introduction.md
      - 例题: pwn/race-condition/problem.md
  - Executable:
    - ELF 文件:
      - ELF文件基本结构: executable/elf/elf_structure.md
      - 程序加载: executable/elf/program_loading.md
      - 程序链接: executable/elf/program_linking.md
      - 程序执行流程: executable/elf/running_overview.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
