name: Preview Site Wrapper

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, edited, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-for-netlify"
  triger-previewing-site:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Triger Inner workflow
        run: echo "triger inner workflow"
